(()=>{
'use strict';
const clamp=(n,a,b)=>Math.min(b,Math.max(a,n));
const nice=(n)=>{if(!Number.isFinite(n))return'--';const a=Math.abs(n);return n.toLocaleString('en-US',{maximumFractionDigits:a>=1000?2:a>=1?4:8})};
class AtlasChart{
 constructor(canvas,overlay,options={}){
  this.canvas=canvas;this.overlay=overlay;this.ctx=canvas.getContext('2d');this.octx=overlay.getContext('2d');this.options={ma:true,ema:false,boll:false,volume:true,...options};
  this.data=[];this.visibleCount=100;this.offset=0;this.hoverIndex=-1;this.selectedIndex=-1;this.drag=null;this.pointers=new Map();this.pinch=null;this.raf=0;this.bounds={};
  this.onSelect=null;this.onHover=null;this.onViewChange=null;this.resizeObserver=new ResizeObserver(()=>this.resize());this.resizeObserver.observe(canvas.parentElement);this.bind();this.resize();
 }
 bind(){
  const el=this.overlay;
  el.addEventListener('pointerdown',e=>{el.setPointerCapture?.(e.pointerId);this.pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(this.pointers.size===2){const p=[...this.pointers.values()];this.pinch={dist:Math.hypot(p[0].x-p[1].x,p[0].y-p[1].y),count:this.visibleCount};return}this.drag={x:e.clientX,y:e.clientY,startOffset:this.offset,moved:false,time:performance.now()}});
  el.addEventListener('pointermove',e=>{if(this.pointers.has(e.pointerId))this.pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(this.pointers.size===2&&this.pinch){const p=[...this.pointers.values()],dist=Math.hypot(p[0].x-p[1].x,p[0].y-p[1].y);if(dist>10){this.visibleCount=clamp(Math.round(this.pinch.count*this.pinch.dist/dist),28,Math.min(220,this.data.length||220));this.offset=clamp(this.offset,0,Math.max(0,this.data.length-this.visibleCount));this.schedule();this.onViewChange?.(this.visibleCount)}return}if(this.drag){const dx=e.clientX-this.drag.x;if(Math.abs(dx)>5)this.drag.moved=true;const step=this.bounds.candleW||8;this.offset=clamp(Math.round(this.drag.startOffset-dx/step),0,Math.max(0,this.data.length-this.visibleCount));this.schedule();return}this.updateHover(e.clientX,e.clientY)});
  const finish=e=>{const p=this.drag;this.pointers.delete(e.pointerId);if(this.pointers.size<2)this.pinch=null;if(!p){this.drag=null;return}const moved=p.moved||Math.hypot(e.clientX-p.x,e.clientY-p.y)>10,age=performance.now()-p.time;this.drag=null;if(!moved&&age<900)this.selectAt(e.clientX,e.clientY)};
  el.addEventListener('pointerup',finish);el.addEventListener('pointercancel',e=>{this.pointers.delete(e.pointerId);this.drag=null;this.pinch=null});
  el.addEventListener('pointerleave',()=>{if(!this.drag){this.hoverIndex=-1;this.drawOverlay()}});
  el.addEventListener('wheel',e=>{e.preventDefault();const before=this.visibleCount,factor=e.deltaY>0?1.1:.9;this.visibleCount=clamp(Math.round(this.visibleCount*factor),28,Math.min(220,this.data.length||220));const r=el.getBoundingClientRect(),ratio=clamp((e.clientX-r.left)/(r.width||1),0,1),delta=this.visibleCount-before;this.offset=clamp(Math.round(this.offset+delta*(1-ratio)),0,Math.max(0,this.data.length-this.visibleCount));this.schedule();this.onViewChange?.(this.visibleCount)},{passive:false});
  window.addEventListener('keydown',e=>{if(e.key==='Escape'&&this.selectedIndex>=0){this.selectedIndex=-1;this.drawOverlay()}})
 }
 setData(data){this.data=(data||[]).slice().sort((a,b)=>a.time-b.time);this.offset=0;this.visibleCount=clamp(this.visibleCount,28,Math.min(120,this.data.length||120));this.schedule()}
 update(c){if(!c)return;const last=this.data.at(-1);if(last&&last.time===c.time)this.data[this.data.length-1]=c;else if(!last||c.time>last.time)this.data.push(c);if(this.data.length>600)this.data.shift();this.schedule()}
 setIndicator(name,on){this.options[name]=on;this.schedule()}
 fit(){this.offset=0;this.visibleCount=clamp(Math.min(100,this.data.length),28,220);this.schedule()}
 resize(){const host=this.canvas.parentElement,r=host.getBoundingClientRect(),d=Math.min(2,devicePixelRatio||1);if(!r.width||!r.height)return;for(const c of [this.canvas,this.overlay]){c.width=Math.round(r.width*d);c.height=Math.round(r.height*d);c.style.width=r.width+'px';c.style.height=r.height+'px'}this.dpr=d;this.width=r.width;this.height=r.height;this.schedule()}
 schedule(){if(this.raf)return;this.raf=requestAnimationFrame(()=>{this.raf=0;this.draw()})}
 visible(){const end=Math.max(0,this.data.length-this.offset),start=Math.max(0,end-this.visibleCount);return{items:this.data.slice(start,end),start,end}}
 calcBounds(items){const pad={l:10,r:68,t:14,b:this.options.volume?83:38},mainH=this.height-pad.t-pad.b;let min=Math.min(...items.map(x=>x.low)),max=Math.max(...items.map(x=>x.high));if(!Number.isFinite(min)||!Number.isFinite(max)){min=0;max=1}const spread=max-min||Math.max(1,max*.01);min-=spread*.08;max+=spread*.08;const plotW=this.width-pad.l-pad.r,candleW=plotW/Math.max(1,items.length);return{...pad,mainH,min,max,spread:max-min,plotW,candleW,volumeTop:pad.t+mainH+12,volumeH:this.options.volume?55:0}}
 yFor(price,b){return b.t+(b.max-price)/b.spread*b.mainH}
 xFor(i,b){return b.l+(i+.5)*b.candleW}
 draw(){const d=this.dpr||1,ctx=this.ctx,w=this.width||1,h=this.height||1;ctx.setTransform(d,0,0,d,0,0);ctx.clearRect(0,0,w,h);const {items,start}=this.visible();if(items.length<2)return;const b=this.bounds=this.calcBounds(items);const css=getComputedStyle(document.body),text=css.getPropertyValue('--muted').trim()||'#7e8997',line=css.getPropertyValue('--line').trim()||'rgba(44,58,78,.11)',green=css.getPropertyValue('--green').trim()||'#13b887',red=css.getPropertyValue('--red').trim()||'#ec5a70';
  ctx.font='10px -apple-system,BlinkMacSystemFont,sans-serif';ctx.textBaseline='middle';ctx.lineWidth=1;
  for(let i=0;i<=5;i++){const y=b.t+b.mainH*i/5,price=b.max-b.spread*i/5;ctx.strokeStyle=line;ctx.beginPath();ctx.moveTo(b.l,y+.5);ctx.lineTo(w-b.r,y+.5);ctx.stroke();ctx.fillStyle=text;ctx.textAlign='left';ctx.fillText(nice(price),w-b.r+9,y)}
  const timeSteps=Math.max(3,Math.min(6,Math.floor(b.plotW/130)));for(let i=0;i<timeSteps;i++){const idx=Math.round((items.length-1)*i/(timeSteps-1)),x=this.xFor(idx,b);ctx.strokeStyle=line;ctx.beginPath();ctx.moveTo(x+.5,b.t);ctx.lineTo(x+.5,b.t+b.mainH+b.volumeH+12);ctx.stroke();const dt=new Date(items[idx].time*1000);ctx.fillStyle=text;ctx.textAlign='center';ctx.fillText(`${String(dt.getMonth()+1).padStart(2,'0')}-${String(dt.getDate()).padStart(2,'0')} ${String(dt.getHours()).padStart(2,'0')}:${String(dt.getMinutes()).padStart(2,'0')}`,x,h-13)}
  if(this.options.volume){const vmax=Math.max(1,...items.map(x=>x.volume||0));items.forEach((c,i)=>{const x=this.xFor(i,b),bw=Math.max(1,Math.min(8,b.candleW*.62)),vh=(c.volume||0)/vmax*b.volumeH;ctx.fillStyle=c.close>=c.open?green+'55':red+'55';ctx.fillRect(x-bw/2,b.volumeTop+b.volumeH-vh,bw,vh)})}
  items.forEach((c,i)=>{const x=this.xFor(i,b),yo=this.yFor(c.open,b),yc=this.yFor(c.close,b),yh=this.yFor(c.high,b),yl=this.yFor(c.low,b),up=c.close>=c.open,col=up?green:red,bw=Math.max(2,Math.min(9,b.candleW*.64));ctx.strokeStyle=col;ctx.beginPath();ctx.moveTo(x,yh);ctx.lineTo(x,yl);ctx.stroke();ctx.fillStyle=col;const top=Math.min(yo,yc),bh=Math.max(1.5,Math.abs(yc-yo));ctx.fillRect(x-bw/2,top,bw,bh)});
  const close=items.map(x=>x.close);if(this.options.ma)this.drawLine(this.sma(close,7),items,b,'#e7a92f',1.45);if(this.options.ema)this.drawLine(this.ema(close,12),items,b,'#6c7cff',1.35);if(this.options.boll){const bo=this.boll(close,20);this.drawLine(bo.upper,items,b,'#7b8cf7',1);this.drawLine(bo.mid,items,b,'#8f73dc',1);this.drawLine(bo.lower,items,b,'#7b8cf7',1)}
  const last=items.at(-1),ly=this.yFor(last.close,b);ctx.setLineDash([4,4]);ctx.strokeStyle=last.close>=last.open?green:red;ctx.beginPath();ctx.moveTo(b.l,ly);ctx.lineTo(w-b.r,ly);ctx.stroke();ctx.setLineDash([]);ctx.fillStyle=last.close>=last.open?green:red;ctx.fillRect(w-b.r,ly-12,b.r,24);ctx.fillStyle='#fff';ctx.textAlign='center';ctx.font='700 10px -apple-system';ctx.fillText(nice(last.close),w-b.r/2,ly);
  this.startIndex=start;this.drawOverlay();
 }
 drawLine(vals,items,b,color,width){const ctx=this.ctx;ctx.strokeStyle=color;ctx.lineWidth=width;ctx.beginPath();let open=false;vals.forEach((v,i)=>{if(v==null)return;const x=this.xFor(i,b),y=this.yFor(v,b);if(!open){ctx.moveTo(x,y);open=true}else ctx.lineTo(x,y)});ctx.stroke();ctx.lineWidth=1}
 sma(a,n){return a.map((_,i)=>i<n-1?null:a.slice(i-n+1,i+1).reduce((s,v)=>s+v,0)/n)}
 ema(a,n){let p=null,k=2/(n+1);return a.map(v=>(p=p==null?v:v*k+p*(1-k)))}
 boll(a,n){const mid=[],upper=[],lower=[];a.forEach((_,i)=>{if(i<n-1){mid.push(null);upper.push(null);lower.push(null);return}const x=a.slice(i-n+1,i+1),m=x.reduce((s,v)=>s+v,0)/n,sd=Math.sqrt(x.reduce((s,v)=>s+(v-m)**2,0)/n);mid.push(m);upper.push(m+sd*2);lower.push(m-sd*2)});return{mid,upper,lower}}
 indexAt(clientX){const r=this.overlay.getBoundingClientRect(),x=clientX-r.left,b=this.bounds,local=Math.floor((x-b.l)/b.candleW);return clamp(local,0,Math.max(0,this.visible().items.length-1))}
 updateHover(x,y){const r=this.overlay.getBoundingClientRect();if(x<r.left||x>r.right||y<r.top||y>r.bottom)return;this.hoverIndex=this.indexAt(x);this.drawOverlay();const item=this.visible().items[this.hoverIndex];if(item)this.onHover?.(item)}
 selectAt(x,y){const r=this.overlay.getBoundingClientRect();if(y<r.top||y>r.bottom)return;this.selectedIndex=this.indexAt(x);const item=this.visible().items[this.selectedIndex];if(item){this.onSelect?.(item);this.drawOverlay()}}
 drawOverlay(){const d=this.dpr||1,ctx=this.octx,w=this.width||1,h=this.height||1;ctx.setTransform(d,0,0,d,0,0);ctx.clearRect(0,0,w,h);const i=this.selectedIndex>=0?this.selectedIndex:this.hoverIndex,{items}=this.visible();if(i<0||!items[i]||!this.bounds.candleW)return;const b=this.bounds,c=items[i],x=this.xFor(i,b),y=this.yFor(c.close,b),dark=document.body.classList.contains('dark');ctx.strokeStyle=dark?'rgba(184,197,216,.55)':'rgba(75,88,107,.45)';ctx.setLineDash([4,4]);ctx.beginPath();ctx.moveTo(x,b.t);ctx.lineTo(x,b.t+b.mainH+(this.options.volume?b.volumeH+12:0));ctx.moveTo(b.l,y);ctx.lineTo(w-b.r,y);ctx.stroke();ctx.setLineDash([]);ctx.fillStyle=dark?'rgba(16,22,31,.94)':'rgba(255,255,255,.95)';ctx.strokeStyle=dark?'rgba(176,190,209,.18)':'rgba(41,54,73,.14)';const boxW=176,boxH=88,left=x>w/2?Math.max(8,x-boxW-14):Math.min(w-boxW-8,x+14),top=clamp(y-boxH/2,8,h-boxH-35);this.roundRect(ctx,left,top,boxW,boxH,10);ctx.fill();ctx.stroke();ctx.fillStyle=dark?'#f1f4f8':'#111722';ctx.textAlign='left';ctx.font='700 10px -apple-system';const dt=new Date(c.time*1000);ctx.fillText(dt.toLocaleString('zh-CN',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false}),left+10,top+14);ctx.font='9px -apple-system';const chg=(c.close-c.open)/c.open*100,lines=[`开 ${nice(c.open)}   高 ${nice(c.high)}`,`低 ${nice(c.low)}   收 ${nice(c.close)}`,`涨跌 ${chg>=0?'+':''}${chg.toFixed(2)}%`, `成交量 ${new Intl.NumberFormat('en-US',{notation:'compact',maximumFractionDigits:2}).format(c.volume||0)}`];lines.forEach((t,j)=>{ctx.fillStyle=j===2?(chg>=0?'#13b887':'#ec5a70'):(dark?'#aab5c4':'#596576');ctx.fillText(t,left+10,top+32+j*14)})}
 roundRect(ctx,x,y,w,h,r){ctx.beginPath();ctx.moveTo(x+r,y);ctx.arcTo(x+w,y,x+w,y+h,r);ctx.arcTo(x+w,y+h,x,y+h,r);ctx.arcTo(x,y+h,x,y,r);ctx.arcTo(x,y,x+w,y,r);ctx.closePath()}
 destroy(){this.resizeObserver.disconnect();cancelAnimationFrame(this.raf)}
}
window.AtlasChart=AtlasChart;
})();
