(()=>{'use strict';const X=window.ATLAS_V11=window.ATLAS_V11||{};
function h(tag,cls,html=''){const n=document.createElement(tag);n.className=cls;n.innerHTML=html;return n}
function theme(){document.body.classList.add('light','v11-pearl');try{localStorage.setItem('atlas-v7-theme','light')}catch{}const meta=document.querySelector('meta[name="theme-color"]');if(meta)meta.content='#f4f6f8';const btn=document.querySelector('#themeBtn');if(btn){btn.title='切换明暗主题';btn.textContent='◐';btn.addEventListener('click',()=>setTimeout(()=>{document.body.classList.toggle('v11-pearl',document.body.classList.contains('light'));if(meta)meta.content=document.body.classList.contains('light')?'#f4f6f8':'#07090d'},0))}}
function brand(){document.title='ATLAS X V11｜Pearl Glass 交易终端';const small=document.querySelector('.brand small');if(small)small.textContent='V11 PEARL TERMINAL';document.querySelector('.v10-badge')?.remove();document.querySelector('.v9-badge')?.remove();const live=document.querySelector('#livePill');if(live&&!document.querySelector('.v11-badge'))live.after(h('span','v11-badge','<i></i> V11 PEARL'));const demo=document.querySelector('.demo-badge');if(demo)demo.textContent='REALTIME DATA · SIMULATED EXECUTION'}
function compactHeader(){const top=document.querySelector('.topbar');if(!top||document.querySelector('.v11-mobile-brand-sub'))return;const sub=h('span','v11-mobile-brand-sub','PRO TERMINAL');document.querySelector('.brand strong')?.after(sub);const favorite=document.querySelector('#favoriteBtn');if(favorite){favorite.setAttribute('aria-label','自选');favorite.title='加入或移出自选';const sync=()=>favorite.dataset.star=favorite.textContent.includes('★')?'★':'☆';sync();new MutationObserver(sync).observe(favorite,{childList:true,subtree:true,characterData:true})}}
function cleanChart(){document.querySelector('.chart-status')?.classList.add('v11-hidden-status');const headline=document.querySelector('#v10ChartHeadline');if(headline){const title=headline.querySelector('div:first-child span');if(title)title.textContent='MARKET CHART';const stats=headline.querySelector('.v10-headline-stats');if(stats)stats.innerHTML='<span>触控 <b>轻点K线锁定数据</b></span><span>手势 <b>拖动 / 双指缩放</b></span><span>状态 <b id="v10ChartState">实时连接</b></span>'}const tools=document.querySelector('.indicator-tools');if(tools&&!document.querySelector('.v11-tool-label'))tools.prepend(h('span','v11-tool-label','指标'))}
function quoteCard(){const bar=document.querySelector('.pairbar');if(!bar||document.querySelector('.v11-quote-label'))return;const price=document.querySelector('.pair-price');if(price)price.prepend(h('span','v11-quote-label','最新价格'));const map=[['change24','v11-kpi-change'],['high24','v11-kpi-high'],['low24','v11-kpi-low'],['vol24','v11-kpi-volume']];map.forEach(([id,cls])=>document.querySelector('#'+id)?.closest('.pair-kpi')?.classList.add(cls));const change=document.querySelector('#change24')?.closest('.pair-kpi');if(change)change.classList.add('v11-primary-kpi')}
function nav(){document.querySelectorAll('.mobile-nav button').forEach(b=>{const text=[...b.childNodes].find(n=>n.nodeType===3);if(text&&text.textContent.trim()==='AI')text.textContent='智能'})}
function bind(){theme();brand();compactHeader();cleanChart();quoteCard();nav();document.body.classList.add('v11-ready');setTimeout(()=>{window.__ATLAS_V7?.chart?.resize?.();X.bindTap?.(window.__ATLAS_V7?.chart)},160)}
Object.assign(X,{bindUI:bind});
})();
