class AccountEngine{
 constructor(priceFn){this.key='atlas-x-v7-account';this.priceFn=priceFn;this.listeners=[];this.data=this.load()}
 fresh(){return{initial:100000,cash:100000,positions:{},orders:[],trades:[],journal:[],fees:0,equityHistory:[{t:Date.now(),v:100000}],createdAt:Date.now()}}
 load(){try{const d=JSON.parse(localStorage.getItem(this.key));return d?{...this.fresh(),...d,positions:d.positions||{},orders:d.orders||[],trades:d.trades||[],journal:d.journal||[],equityHistory:d.equityHistory||[]}:this.fresh()}catch{return this.fresh()}}
 save(){try{localStorage.setItem(this.key,JSON.stringify(this.data))}catch{}}
 on(fn){this.listeners.push(fn)}emit(){this.save();this.listeners.forEach(fn=>{try{fn(this.snapshot())}catch(e){console.error(e)}})}reset(){this.data=this.fresh();this.emit()}
 addFunds(v){const n=+v;if(!n||n<=0)return false;this.data.cash+=n;this.data.initial+=n;this.data.journal.unshift({id:uid(),type:'资金',text:`增加模拟资金 ${fmt(n,2)} USDT`,ts:Date.now()});this.emit();return true}
 price(instId){return +(this.priceFn(instId)||0)}
 snapshot(){let spot=0,margin=0,unreal=0;for(const p of Object.values(this.data.positions)){const px=this.price(p.instId)||p.avg;if(p.type==='spot'){spot+=px*p.qty;unreal+=(px-p.avg)*p.qty}else{margin+=p.margin;unreal+=(px-p.avg)*p.qty}}const equity=this.data.cash+spot+margin+unreal,ret=this.data.initial?(equity-this.data.initial)/this.data.initial*100:0;return{...this.data,equity,spot,margin,positionValue:spot+margin,unrealized:unreal,returnRate:ret}}
 available(){return this.data.cash}
 order(i){const o={id:uid(),instId:i.instId,base:i.base,product:i.product||'spot',type:i.type||'limit',side:i.side||'buy',amount:+i.amount,price:+i.price,trigger:+i.trigger||0,leverage:+i.leverage||1,tp:+i.tp||0,sl:+i.sl||0,triggerAbove:i.triggerAbove===true,ocoGroup:i.ocoGroup||'',strategyType:i.strategyType||'',displayAmount:+i.displayAmount||0,status:'open',createdAt:Date.now()};if(!o.amount||o.amount<=0)return{ok:false,error:'请输入有效数量'};const px=this.price(o.instId);if(!px)return{ok:false,error:'实时价格尚未加载'};if(o.type==='market')return this.execute(o,px);this.data.orders.unshift(o);this.data.journal.unshift({id:uid(),type:'委托',text:`提交${o.product==='spot'?'现货':'永续'}${o.side==='buy'?'买入/做多':'卖出/做空'}委托 ${o.amount} ${o.base}`,ts:Date.now()});this.emit();return{ok:true,order:o}}
 execute(o,fill){const total=o.amount*fill,feeRate=o.product==='spot'?.001:.0005,fee=total*feeRate;let realized=0;if(o.product==='spot'){const key=`${o.base}-SPOT`,p=this.data.positions[key];if(o.side==='buy'){if(this.data.cash<total+fee)return{ok:false,error:'模拟余额不足'};this.data.cash-=total+fee;const q=p?.qty||0,c=p?q*p.avg:0;this.data.positions[key]={key,type:'spot',instId:o.instId,base:o.base,qty:q+o.amount,avg:(c+total)/(q+o.amount),tp:o.tp,sl:o.sl}}else{if(!p||p.qty+1e-12<o.amount)return{ok:false,error:`${o.base} 可用持仓不足`};realized=(fill-p.avg)*o.amount-fee;this.data.cash+=total-fee;p.qty-=o.amount;if(p.qty<=1e-10)delete this.data.positions[key]}}
 else{const key=`${o.base}-PERP`,signed=o.side==='buy'?o.amount:-o.amount,lev=Math.max(1,o.leverage||1);let p=this.data.positions[key];if(!p||Math.sign(p.qty)===Math.sign(signed)){const needed=total/lev+fee;if(this.data.cash<needed)return{ok:false,error:'模拟保证金不足'};this.data.cash-=needed;if(!p)this.data.positions[key]={key,type:'perp',instId:o.instId,base:o.base,qty:signed,avg:fill,leverage:lev,margin:total/lev,tp:o.tp,sl:o.sl};else{const a=Math.abs(p.qty),b=Math.abs(signed);p.avg=(p.avg*a+fill*b)/(a+b);p.qty+=signed;p.margin+=total/lev;p.leverage=lev;p.tp=o.tp||p.tp;p.sl=o.sl||p.sl}}else{const close=Math.min(Math.abs(p.qty),Math.abs(signed)),dir=Math.sign(p.qty),release=p.margin*(close/Math.abs(p.qty));realized=(fill-p.avg)*close*dir-fee;this.data.cash+=release+realized;p.margin-=release;p.qty-=dir*close;const remain=Math.abs(signed)-close;if(Math.abs(p.qty)<=1e-10)delete this.data.positions[key];if(remain>1e-10){const need=remain*fill/lev+fee;if(this.data.cash>=need){this.data.cash-=need;this.data.positions[key]={key,type:'perp',instId:o.instId,base:o.base,qty:Math.sign(signed)*remain,avg:fill,leverage:lev,margin:remain*fill/lev,tp:o.tp,sl:o.sl}}}}}
 this.data.fees+=fee;const tr={...o,status:'filled',fillPrice:fill,fee,realizedPnl:realized,filledAt:Date.now()};this.data.trades.unshift(tr);this.data.orders=this.data.orders.filter(x=>x.id!==o.id);this.data.journal.unshift({id:uid(),type:'成交',text:`${o.side==='buy'?'买入/做多':'卖出/做空'} ${o.amount} ${o.base} 成交于 ${fill}`,ts:Date.now(),pnl:realized});this.record();this.emit();return{ok:true,trade:tr}}
 check(instId){const px=this.price(instId);if(!px)return;for(const o of [...this.data.orders]){if(o.instId!==instId)continue;let hit=o.type==='limit'?(o.side==='buy'?px<=o.price:px>=o.price):(o.triggerAbove?px>=o.trigger:px<=o.trigger);if(hit){const group=o.ocoGroup;this.execute(o,o.type==='limit'?o.price:px);if(group){this.data.orders=this.data.orders.filter(x=>x.ocoGroup!==group);this.emit()}}}for(const p of Object.values({...this.data.positions})){if(p.instId!==instId)continue;const long=p.type==='spot'||p.qty>0;if(p.tp&&((long&&px>=p.tp)||(!long&&px<=p.tp)))this.close(p.key,'止盈触发');else if(p.sl&&((long&&px<=p.sl)||(!long&&px>=p.sl)))this.close(p.key,'止损触发')}}
 cancel(id){const o=this.data.orders.find(x=>x.id===id);if(!o)return;this.data.orders=this.data.orders.filter(x=>x.id!==id);this.data.journal.unshift({id:uid(),type:'撤单',text:`撤销 ${o.base} 委托`,ts:Date.now()});this.emit()}
 close(key,reason='手动平仓'){const p=this.data.positions[key];if(!p)return{ok:false,error:'持仓不存在'};const o={id:uid(),instId:p.instId,base:p.base,product:p.type,type:'market',side:p.type==='spot'?'sell':p.qty>0?'sell':'buy',amount:Math.abs(p.qty),leverage:p.leverage||1,createdAt:Date.now()};const r=this.execute(o,this.price(p.instId)||p.avg);if(r.ok){this.data.journal.unshift({id:uid(),type:'平仓',text:`${reason}：${p.base}`,ts:Date.now()});this.save()}return r}
 record(){const s=this.snapshot(),last=this.data.equityHistory.at(-1);if(!last||Date.now()-last.t>30000)this.data.equityHistory.push({t:Date.now(),v:s.equity});else last.v=s.equity;if(this.data.equityHistory.length>500)this.data.equityHistory.shift()}
 metrics(){const s=this.snapshot(),closed=this.data.trades.filter(x=>Number.isFinite(x.realizedPnl)&&x.realizedPnl!==0),wins=closed.filter(x=>x.realizedPnl>0),loss=closed.filter(x=>x.realizedPnl<0),gw=wins.reduce((a,x)=>a+x.realizedPnl,0),gl=Math.abs(loss.reduce((a,x)=>a+x.realizedPnl,0));let peak=this.data.initial,maxDD=0,streak=0,maxStreak=0;for(const x of this.data.equityHistory){peak=Math.max(peak,x.v);maxDD=Math.min(maxDD,(x.v-peak)/peak*100)}for(const x of closed){if(x.realizedPnl<0){streak++;maxStreak=Math.max(maxStreak,streak)}else streak=0}const alloc=[];for(const p of Object.values(this.data.positions)){const px=this.price(p.instId)||p.avg,value=p.type==='spot'?px*p.qty:p.margin+(px-p.avg)*p.qty;alloc.push({name:p.base,value:Math.max(0,value),type:p.type})}alloc.push({name:'USDT',value:Math.max(0,this.data.cash),type:'cash'});const maxAlloc=s.equity?Math.max(0,...alloc.filter(x=>x.name!=='USDT').map(x=>x.value/s.equity*100)):0,perp=Object.values(this.data.positions).filter(x=>x.type==='perp').reduce((a,p)=>a+Math.abs(p.qty)*(this.price(p.instId)||p.avg),0),risk=Math.round(Math.min(100,maxAlloc*.7+Math.min(40,perp/Math.max(1,s.equity)*14)+Math.min(15,Math.abs(maxDD))));return{...s,closed,wins,loss,winRate:closed.length?wins.length/closed.length*100:null,profitFactor:gl?gw/gl:null,maxDrawdown:maxDD,lossStreak:maxStreak,allocation:alloc,maxAllocation:maxAlloc,perpExposure:perp,risk}}
 export(){const blob=new Blob([JSON.stringify({generatedAt:new Date().toISOString(),account:this.data,metrics:this.metrics(),notice:'模拟账户数据，不构成投资建议。'},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`atlas-x-v7-${Date.now()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
}
