function bind(){
 $$('[data-route]').forEach(b=>b.onclick=()=>route(b.dataset.route));$('#menuBtn').onclick=()=>$('#sidebar').classList.toggle('show');
 $('#themeBtn').onclick=()=>{document.body.classList.toggle('light');localStorage.setItem('atlas-v7-theme',document.body.classList.contains('light')?'light':'dark');chart.restyle();drawDepth();drawAssets()};if(localStorage.getItem('atlas-v7-theme')==='light')document.body.classList.add('light');
 $('#focusBtn').onclick=()=>{document.body.classList.toggle('focus');setTimeout(()=>chart.resize(),120)};
 $('#commandOpen').onclick=()=>{$('#command').classList.add('show');$('#commandInput').focus();renderCommand()};$('#command').onclick=e=>{if(e.target===$('#command'))$('#command').classList.remove('show')};$('#commandInput').oninput=renderCommand;document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();$('#commandOpen').click()}if(e.key==='Escape'){$('#command').classList.remove('show');$('#pairMenu').classList.remove('show')}});
 $('#pairSelectBtn').onclick=e=>{const r=e.currentTarget.getBoundingClientRect(),m=$('#pairMenu');m.style.left=`${Math.min(r.left,innerWidth-325)}px`;m.style.top=`${r.bottom+4}px`;m.classList.toggle('show');pairMenuType=market.product;$$('#pairTypeTabs button').forEach(x=>x.classList.toggle('active',x.dataset.pairtype===pairMenuType));renderPairMenu($('#pairSearch').value)};document.addEventListener('click',e=>{if(!e.target.closest('.pair-select-wrap')&&!e.target.closest('#pairMenu'))$('#pairMenu').classList.remove('show')});$('#pairSearch').oninput=e=>renderPairMenu(e.target.value);$$('#pairTypeTabs button').forEach(b=>b.onclick=()=>{pairMenuType=b.dataset.pairtype;$$('#pairTypeTabs button').forEach(x=>x.classList.toggle('active',x===b));renderPairMenu($('#pairSearch').value)});
 $('#watchSearch').oninput=renderWatch;$$('[data-watch]').forEach(b=>b.onclick=()=>{watchMode=b.dataset.watch;$$('[data-watch]').forEach(x=>x.classList.toggle('active',x===b));renderWatch()});$('#favoriteBtn').onclick=()=>{const id=pair().instId;favorites.has(id)?favorites.delete(id):favorites.add(id);localStorage.setItem('atlas-v7-favs',JSON.stringify([...favorites]));renderCurrent();renderWatch();toast(favorites.has(id)?'已加入自选':'已移出自选')};
 $$('#timeframes button').forEach(b=>b.onclick=async()=>{$$('#timeframes button').forEach(x=>x.classList.toggle('active',x===b));$('#chartLoading').classList.remove('hidden');try{await market.setBar(b.dataset.bar)}catch{toast('K线周期加载失败')}});$('#maBtn').onclick=()=>$('#maBtn').classList.toggle('active',chart.toggleMA());$('#volumeBtn').onclick=()=>$('#volumeBtn').classList.toggle('active',chart.toggleVolume());$('#fitBtn').onclick=()=>chart.fit();$('#realtimeBtn').onclick=()=>chart.realtime();$('#fullscreenBtn').onclick=()=>{const p=$('#chartPanel');p.classList.toggle('chart-fullscreen');$('#fullscreenBtn').textContent=p.classList.contains('chart-fullscreen')?'退出全屏':'全屏';setTimeout(()=>chart.resize(),100)};
 $$('#marketTabs button').forEach(b=>b.onclick=()=>{$$('#marketTabs button').forEach(x=>x.classList.toggle('active',x===b));$$('.market-view').forEach(x=>x.classList.toggle('active',x.id===`market-${b.dataset.marketTab}`));if(b.dataset.marketTab==='depth')drawDepth()});
 $$('#productTabs button').forEach(b=>b.onclick=async()=>{if(b.dataset.product===market.product)return;await selectPair(market.base,b.dataset.product)});$$('#orderTabs button').forEach(b=>b.onclick=()=>{orderType=b.dataset.order;$$('#orderTabs button').forEach(x=>x.classList.toggle('active',x===b));updateOrderForm()});$$('#sideTabs button').forEach(b=>b.onclick=()=>{side=b.dataset.side;$$('#sideTabs button').forEach(x=>x.classList.toggle('active',x===b));updateOrderForm()});['orderPrice','orderAmount','triggerPrice','leverage','takeProfit','stopLoss','algoParamA','algoParamB'].forEach(id=>$(`#${id}`)?.addEventListener('input',updateOrderForm));$('#amountSlider').oninput=e=>{$('#orderAmount').value=sliderAmount(e.target.value).toFixed(pair().base==='BTC'?6:4);updateOrderForm()};$('#tpCheck').onchange=e=>$('#advancedFields').classList.toggle('hidden',!e.target.checked);$('#advancedBtn').onclick=()=>{$('#tpCheck').checked=!$('#tpCheck').checked;$('#advancedFields').classList.toggle('hidden',!$('#tpCheck').checked)};$('#submitOrder').onclick=placeOrder;
 $$('[data-position]').forEach(b=>b.onclick=()=>{positionTab=b.dataset.position;$$('[data-position]').forEach(x=>x.classList.toggle('active',x===b));renderPositions()});$('#exportBtn').onclick=()=>{account.export();toast('模拟账户报告已导出')};
 $('#marketSearch').oninput=renderMarkets;$$('[data-filter]').forEach(b=>b.onclick=()=>{marketFilter=b.dataset.filter;$$('[data-filter]').forEach(x=>x.classList.toggle('active',x===b));renderMarkets()});
 $('#resetBtn').onclick=()=>$('#resetModal').hidden=false;$$('[data-close-modal]').forEach(b=>b.onclick=()=>b.closest('.modal').hidden=true);$('#confirmReset').onclick=()=>{account.reset();$('#resetModal').hidden=true;toast('模拟账户已重置')};$('#depositDemoBtn').onclick=()=>$('#fundModal').hidden=false;$('#confirmFund').onclick=()=>{if(account.addFunds($('#fundAmount').value)){toast('模拟资金已增加');$('#fundModal').hidden=true}else toast('请输入有效金额')};
 $('#newStrategyBtn').onclick=()=>toast('策略参数创建器将在后端版开放');$('#refreshAnalyticsBtn').onclick=()=>{renderAnalytics();toast('分析结果已更新')};$('#copyReportBtn').onclick=async()=>{try{await navigator.clipboard.writeText($('#aiReport').textContent);toast('诊断摘要已复制')}catch{toast('当前浏览器不允许复制')}};
 window.addEventListener('resize',()=>{chart.resize();drawDepth();if($('#page-assets').classList.contains('active'))drawAssets()})
}
market.on((type,payload)=>{if(type==='status')renderStatus(payload);if(type==='markets'){renderTicker();renderWatch();renderMarkets();renderCurrent()}if(type==='ticker'){if(payload.id===pair().instId){renderCurrent();account.check(payload.id);renderAccount()}renderTicker();renderWatch()}if(type==='candles'){chart.setData(payload);ensureExtraSeries();refreshExtraSeries();$('#chartLoading').classList.add('hidden')}if(type==='candle'){chart.update(payload);refreshExtraSeries();account.check(pair().instId);if($('#page-copilot')?.classList.contains('active'))renderCopilot()}if(type==='book')renderBook();if(type==='trades')renderTrades();if(type==='derivatives'){renderCurrent();updateFundingCountdown()}if(type==='pair'){renderAll()}});account.on(()=>renderAccount());
async function init(){bind();bindV7();renderStrategies();renderPairMenu();renderWatch();renderMarkets();renderPositions();renderAccount();updateOrderForm();try{await ensureCharts();chart.init();await market.init();renderAll();$('#chartLoading').classList.add('hidden')}catch(e){console.error(e);$('#chartLoading').innerHTML='<span>实时行情或图表加载失败，请刷新页面重试</span>';toast('初始化失败，请检查网络后刷新')}}
init();
