(()=>{
'use strict';
const V8_KEY='atlas-x-v8-settings',ALERT_KEY='atlas-x-v8-alerts',DRAW_KEY='atlas-x-v8-drawings';
const state={drawMode:'',drawStart:null,drawings:load(DRAW_KEY,[]),alerts:load(ALERT_KEY,[]),triggered:new Set(),settings:load(V8_KEY,{marginMode:'cross',tif:'GTC',positionMode:'net'})};
function load(k,f){try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}}
function save(k,v){try{localStorage.setItem(k,JSON.stringify(v))}catch{}}
function el(tag,attrs={},html=''){const n=document.createElement(tag);Object.entries(attrs).forEach(([k,v])=>k==='class'?n.className=v:k.startsWith('data-')?n.setAttribute(k,v):n[k]=v);if(html)n.innerHTML=html;return n}
function v8toast(msg){if(typeof toast==='function')toast(msg)}
function currentPair(){return window.__ATLAS_V7?.market?.pair?.()||null}
function currentPrice(){const p=currentPair();return p?window.__ATLAS_V7.market.get(p.instId).last:0}
function orderBookFill(side,amount,limitPrice=null){const book=window.__ATLAS_V7.market.book||{},rows=(side==='buy'?book.asks:book.bids)||[];let left=amount,notional=0,filled=0;for(const row of rows){const price=+row[0],qty=+row[1];if(limitPrice!==null&&((side==='buy'&&price>limitPrice)||(side==='sell'&&price<limitPrice)))break;const take=Math.min(left,qty);if(take<=0)continue;notional+=take*price;filled+=take;left-=take;if(left<=1e-12)break}const fallback=currentPrice();return{filled,remaining:Math.max(0,amount-filled),avg:filled?notional/filled:fallback,available:rows.reduce((s,r)=>s+(+r[1]||0),0)}}
function enhanceBrand(){document.title='ATLAS X V8｜专业模拟交易终端';const small=document.querySelector('.brand small');if(small)small.textContent='V8 EXECUTION TERMINAL';const demo=document.querySelector('.demo-badge');if(demo)demo.textContent='DEMO · REALTIME · PRO EXECUTION';const live=document.querySelector('#livePill');if(live&&!document.querySelector('.v8-version'))live.after(el('span',{class:'v8-version'},'<i></i> V8'))}
function addChartTools(){const toolbar=document.querySelector('.indicator-tools');if(!toolbar||document.querySelector('.v8-chart-tools'))return;const wrap=el('div',{class:'v8-chart-tools'});wrap.innerHTML='<button id="v8HorizontalBtn" title="添加当前价水平线">水平线</button><button id="v8TrendBtn" title="点击图表两点绘制趋势线">趋势线</button><button id="v8AlertBtn" title="价格提醒">提醒</button><button id="v8ClearDrawBtn" title="清除绘图">清除</button>';toolbar.append(wrap);document.querySelector('#v8HorizontalBtn').onclick=addHorizontal;document.querySelector('#v8TrendBtn').onclick=()=>setDrawMode(state.drawMode==='trend'?'':'trend');document.querySelector('#v8AlertBtn').onclick=()=>document.querySelector('#v8AlertPanel').classList.toggle('show');document.querySelector('#v8ClearDrawBtn').onclick=clearDrawings}
function addExecutionBox(){const summary=document.querySelector('.order-summary');if(!summary||document.querySelector('.v8-execution-box'))return;const box=el('section',{class:'v8-execution-box'});box.innerHTML='<div class="v8-execution-head"><strong>专业执行设置</strong><span>SIMULATED EXECUTION</span></div><div class="v8-execution-grid"><label class="v8-mini-field"><span>保证金模式</span><select id="v8MarginMode"><option value="cross">全仓</option><option value="isolated">逐仓</option></select></label><label class="v8-mini-field"><span>有效方式</span><select id="v8Tif"><option>GTC</option><option>IOC</option><option>FOK</option></select></label><label class="v8-mini-field"><span>持仓模式</span><select id="v8PositionMode"><option value="net">单向持仓</option><option value="hedge">双向持仓</option></select></label></div><div class="v8-execution-stats"><div><span>盘口可成交</span><b id="v8BookLiquidity">--</b></div><div><span>预计滑点</span><b id="v8Slippage">--</b></div><div><span>执行风险</span><b id="v8ExecutionRisk">等待数量</b></div></div>';summary.before(box);const mm=document.querySelector('#v8MarginMode'),tif=document.querySelector('#v8Tif'),pm=document.querySelector('#v8PositionMode');mm.value=state.settings.marginMode;tif.value=state.settings.tif;pm.value=state.settings.positionMode;[mm,tif,pm].forEach(x=>x.onchange=()=>{state.settings={marginMode:mm.value,tif:tif.value,positionMode:pm.value};save(V8_KEY,state.settings);updateExecutionStats()});['orderAmount','orderPrice','leverage'].forEach(id=>document.querySelector('#'+id)?.addEventListener('input',updateExecutionStats));document.querySelectorAll('#sideTabs button,#orderTabs button,#productTabs button').forEach(b=>b.addEventListener('click',()=>setTimeout(updateExecutionStats,20)))}
function updateExecutionStats(){const amount=+(document.querySelector('#orderAmount')?.value||0),sideValue=typeof side!=='undefined'?side:'buy',px=currentPrice(),fill=orderBookFill(sideValue,amount),liq=document.querySelector('#v8BookLiquidity'),slip=document.querySelector('#v8Slippage'),risk=document.querySelector('#v8ExecutionRisk');if(!liq)return;liq.textContent=amount?`${Math.min(fill.filled,amount).toFixed(6)} / ${amount.toFixed(6)}`:'--';const sp=amount&&px&&fill.avg?Math.abs(fill.avg-px)/px*100:0;slip.textContent=amount?`${sp.toFixed(4)}%`:'--';risk.className='';if(!amount){risk.textContent='等待数量';return}const ratio=fill.available?amount/fill.available:1;if(fill.filled+1e-12<amount){risk.textContent='流动性不足';risk.classList.add('v8-risk-high')}else if(sp>.15||ratio>.35){risk.textContent='较高';risk.classList.add('v8-risk-warn')}else{risk.textContent='正常';risk.classList.add('v8-risk-ok')}}
function patchExecution(){const a=window.__ATLAS_V7?.account;if(!a||a.__v8Patched)return;a.__v8Patched=true;const originalOrder=a.order.bind(a),originalExecute=a.execute.bind(a);a.order=function(input){const tif=document.querySelector('#v8Tif')?.value||'GTC',marginMode=document.querySelector('#v8MarginMode')?.value||'cross',positionMode=document.querySelector('#v8PositionMode')?.value||'net',amount=+input.amount||0,marketPx=this.price(input.instId);input={...input,timeInForce:tif,marginMode,positionMode};if(input.type==='market'){const f=orderBookFill(input.side,amount);if(!f.filled)return{ok:false,error:'盘口流动性不足'};const o={id:uid(),instId:input.instId,base:input.base,product:input.product||'spot',type:'market',side:input.side||'buy',amount:f.filled,price:f.avg,trigger:0,leverage:+input.leverage||1,tp:+input.tp||0,sl:+input.sl||0,status:'open',timeInForce:tif,marginMode,positionMode,createdAt:Date.now(),requestedAmount:amount,slippage:marketPx?Math.abs(f.avg-marketPx)/marketPx*100:0};const r=originalExecute(o,f.avg);if(r.ok){const p=this.data.positions[`${o.base}-${o.product==='spot'?'SPOT':'PERP'}`];if(p){p.marginMode=marginMode;p.positionMode=positionMode}r.trade.execution='market-depth';r.trade.requestedAmount=amount;r.trade.filledAmount=f.filled}return r}
 if((tif==='IOC'||tif==='FOK')&&input.type==='limit'){const best=input.side==='buy'?window.__ATLAS_V7.market.book.asks?.[0]?.[0]:window.__ATLAS_V7.market.book.bids?.[0]?.[0],marketable=best&&((input.side==='buy'&&input.price>=best)||(input.side==='sell'&&input.price<=best));if(!marketable)return{ok:false,error:`${tif} 委托无法立即成交，已取消`};const f=orderBookFill(input.side,amount,+input.price);if(tif==='FOK'&&f.filled+1e-12<amount)return{ok:false,error:'FOK 无法全部成交，已拒绝'};if(!f.filled)return{ok:false,error:'IOC 无可成交数量'};const o={id:uid(),instId:input.instId,base:input.base,product:input.product||'spot',type:'limit',side:input.side||'buy',amount:f.filled,price:+input.price,trigger:0,leverage:+input.leverage||1,tp:+input.tp||0,sl:+input.sl||0,status:'open',timeInForce:tif,marginMode,positionMode,createdAt:Date.now(),requestedAmount:amount};const r=originalExecute(o,f.avg||input.price);if(r.ok){r.trade.execution=tif;r.trade.requestedAmount=amount;r.trade.filledAmount=f.filled;r.trade.remainingAmount=Math.max(0,amount-f.filled);const p=this.data.positions[`${o.base}-${o.product==='spot'?'SPOT':'PERP'}`];if(p){p.marginMode=marginMode;p.positionMode=positionMode}}return r}
 const r=originalOrder(input);if(r.ok&&r.order){r.order.timeInForce=tif;r.order.marginMode=marginMode;r.order.positionMode=positionMode;r.order.filledAmount=0;r.order.remainingAmount=amount;this.save()}return r};a.execute=function(o,fill){const r=originalExecute(o,fill);if(r.ok){const p=this.data.positions[`${o.base}-${o.product==='spot'?'SPOT':'PERP'}`];if(p){p.marginMode=o.marginMode||state.settings.marginMode;p.positionMode=o.positionMode||state.settings.positionMode}}return r}}
function enhancePositions(){if(typeof renderPositions!=='function'||renderPositions.__v8)return;const old=renderPositions;renderPositions=function(){old();document.querySelectorAll('#positionsBody tr').forEach(row=>{const first=row.querySelector('td');if(!first)return;const text=first.textContent||'';const base=(text.match(/BTC|ETH|SOL|BNB|XRP|DOGE|ADA/)||[])[0];if(!base)return;const pos=window.__ATLAS_V7.account.data.positions[`${base}-${text.includes('现货')?'SPOT':'PERP'}`];if(pos&&!first.querySelector('.v8-margin-badge'))first.querySelector('b')?.insertAdjacentHTML('beforeend',`<span class="v8-margin-badge">${pos.marginMode==='isolated'?'逐仓':'全仓'} · ${pos.positionMode==='hedge'?'双向':'单向'}</span>`)});document.querySelectorAll('#positionsBody [data-cancel]').forEach(b=>{const row=b.closest('tr'),id=b.dataset.cancel,o=window.__ATLAS_V7.account.data.orders.find(x=>x.id===id);if(o&&row){const cells=row.querySelectorAll('td');if(cells[4])cells[4].innerHTML=`${o.strategyType||o.type}<br><span class="v8-order-state open">${o.timeInForce||'GTC'} · 等待成交</span>`}})};renderPositions.__v8=true}
function initDrawing(){const host=document.querySelector('#chartHost');if(!host||document.querySelector('#v8DrawingLayer'))return;const canvas=el('canvas',{id:'v8DrawingLayer',class:'v8-drawing-layer'}),hint=el('div',{id:'v8DrawHint',class:'v8-draw-hint'},'点击图表选择趋势线起点');host.append(canvas,hint);canvas.addEventListener('pointerdown',onDrawPoint);new ResizeObserver(resizeDrawing).observe(host);resizeDrawing();redraw()}
function resizeDrawing(){const c=document.querySelector('#v8DrawingLayer'),host=document.querySelector('#chartHost');if(!c||!host)return;const r=host.getBoundingClientRect(),d=Math.min(2,devicePixelRatio||1);c.width=Math.max(1,r.width*d);c.height=Math.max(1,r.height*d);c.style.width=r.width+'px';c.style.height=r.height+'px';c.dataset.dpr=d;redraw()}
function setDrawMode(mode){state.drawMode=mode;state.drawStart=null;const c=document.querySelector('#v8DrawingLayer'),h=document.querySelector('#v8DrawHint'),b=document.querySelector('#v8TrendBtn');c?.classList.toggle('drawing',!!mode);b?.classList.toggle('active',mode==='trend');h?.classList.toggle('show',mode==='trend');if(h&&mode==='trend')h.textContent='点击图表选择趋势线起点'}
function onDrawPoint(e){if(state.drawMode!=='trend')return;const c=e.currentTarget,r=c.getBoundingClientRect(),x=e.clientX-r.left,y=e.clientY-r.top,chartObj=window.__ATLAS_V7.chart,p=chartObj.candles?.coordinateToPrice(y),t=chartObj.chart?.timeScale().coordinateToTime(x);if(p==null||t==null)return;const point={time:t,price:p};if(!state.drawStart){state.drawStart=point;document.querySelector('#v8DrawHint').textContent='再点击一次选择趋势线终点'}else{state.drawings.push({type:'trend',a:state.drawStart,b:point,color:'#7a91ff'});save(DRAW_KEY,state.drawings);setDrawMode('');redraw();v8toast('趋势线已添加')}}
function addHorizontal(){const px=currentPrice();if(!px)return v8toast('实时价格尚未加载');state.drawings.push({type:'horizontal',price:px,color:'#f1ba55'});save(DRAW_KEY,state.drawings);redraw();v8toast('已在当前价格添加水平线')}
function clearDrawings(){state.drawings=[];save(DRAW_KEY,state.drawings);redraw();v8toast('图表绘图已清除')}
function redraw(){const c=document.querySelector('#v8DrawingLayer');if(!c)return;const d=+c.dataset.dpr||1,ctx=c.getContext('2d'),w=c.width/d,h=c.height/d;ctx.setTransform(d,0,0,d,0,0);ctx.clearRect(0,0,w,h);const ch=window.__ATLAS_V7?.chart;if(!ch?.chart||!ch.candles)return;ctx.lineWidth=1.4;for(const dr of state.drawings){ctx.strokeStyle=dr.color||'#7a91ff';ctx.setLineDash(dr.type==='horizontal'?[5,4]:[]);if(dr.type==='horizontal'){const y=ch.candles.priceToCoordinate(dr.price);if(y==null)continue;ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y);ctx.stroke();ctx.fillStyle=ctx.strokeStyle;ctx.font='10px sans-serif';ctx.fillText(Number(dr.price).toLocaleString(),7,Math.max(12,y-5))}else if(dr.type==='trend'){const x1=ch.chart.timeScale().timeToCoordinate(dr.a.time),x2=ch.chart.timeScale().timeToCoordinate(dr.b.time),y1=ch.candles.priceToCoordinate(dr.a.price),y2=ch.candles.priceToCoordinate(dr.b.price);if([x1,x2,y1,y2].some(v=>v==null))continue;ctx.beginPath();ctx.moveTo(x1,y1);ctx.lineTo(x2,y2);ctx.stroke();ctx.fillStyle=ctx.strokeStyle;for(const [x,y] of [[x1,y1],[x2,y2]]){ctx.beginPath();ctx.arc(x,y,3,0,Math.PI*2);ctx.fill()}}}ctx.setLineDash([])}
function patchChart(){const C=typeof ChartController!=='undefined'?ChartController:null;if(!C||C.prototype.__v8)return;C.prototype.__v8=true;const init=C.prototype.init,resize=C.prototype.resize,setData=C.prototype.setData,update=C.prototype.update;C.prototype.init=function(){const r=init.apply(this,arguments);setTimeout(initDrawing,0);return r};C.prototype.resize=function(){const r=resize.apply(this,arguments);setTimeout(resizeDrawing,0);return r};C.prototype.setData=function(){const r=setData.apply(this,arguments);setTimeout(redraw,0);return r};C.prototype.update=function(){const r=update.apply(this,arguments);setTimeout(redraw,0);return r}}
function addAlertPanel(){if(document.querySelector('#v8AlertPanel'))return;const panel=el('section',{id:'v8AlertPanel',class:'v8-alert-panel'});panel.innerHTML='<div class="v8-alert-head"><strong>价格提醒</strong><button id="v8AlertClose">✕</button></div><div class="v8-alert-form"><input id="v8AlertPrice" inputmode="decimal" placeholder="目标价格"><select id="v8AlertDirection"><option value="above">上穿</option><option value="below">下破</option></select><button id="v8AlertCreate">创建提醒</button></div><div class="v8-alert-list" id="v8AlertList"></div>';document.body.append(panel);document.querySelector('#v8AlertClose').onclick=()=>panel.classList.remove('show');document.querySelector('#v8AlertCreate').onclick=createAlert;renderAlerts()}
function createAlert(){const p=currentPair(),price=+(document.querySelector('#v8AlertPrice').value||0),direction=document.querySelector('#v8AlertDirection').value;if(!p||!price)return v8toast('请输入有效提醒价格');state.alerts.unshift({id:uid(),instId:p.instId,base:p.base,price,direction,createdAt:Date.now(),active:true});save(ALERT_KEY,state.alerts);renderAlerts();v8toast('价格提醒已创建')}
function renderAlerts(){const list=document.querySelector('#v8AlertList');if(!list)return;list.innerHTML=state.alerts.length?state.alerts.map(a=>`<div class="v8-alert-item"><span>${a.base} ${a.direction==='above'?'上穿':'下破'} ${Number(a.price).toLocaleString()}<small>${a.active?'监控中':'已触发'}</small></span><button data-v8-alert-remove="${a.id}">删除</button></div>`).join(''):'<div class="empty-cell">暂无价格提醒</div>';list.querySelectorAll('[data-v8-alert-remove]').forEach(b=>b.onclick=()=>{state.alerts=state.alerts.filter(a=>a.id!==b.dataset.v8AlertRemove);save(ALERT_KEY,state.alerts);renderAlerts()})}
function checkAlerts(){const m=window.__ATLAS_V7?.market;if(!m)return;let changed=false;for(const a of state.alerts){if(!a.active)continue;const px=m.get(a.instId).last;if(!px)continue;const hit=a.direction==='above'?px>=a.price:px<=a.price;if(hit){a.active=false;changed=true;v8toast(`价格提醒：${a.base} 已${a.direction==='above'?'上穿':'下破'} ${Number(a.price).toLocaleString()}`);if('Notification'in window&&Notification.permission==='granted')new Notification('ATLAS X 价格提醒',{body:`${a.base} 当前价格 ${px}`})}}if(changed){save(ALERT_KEY,state.alerts);renderAlerts()}}
function bindV8(){enhanceBrand();addChartTools();addExecutionBox();addAlertPanel();patchExecution();enhancePositions();updateExecutionStats();window.__ATLAS_V7.market.on((type)=>{if(type==='ticker'||type==='pair'||type==='book'){checkAlerts();updateExecutionStats();if(type==='pair')setTimeout(redraw,80)}});setInterval(()=>{updateExecutionStats();checkAlerts()},2500);setTimeout(()=>document.querySelector('#v8boot')?.remove(),450)}
patchChart();const originalBindV7=typeof bindV7==='function'?bindV7:null;if(originalBindV7){bindV7=function(){originalBindV7();bindV8()}}else document.addEventListener('DOMContentLoaded',bindV8);
})();
